<?php
/**
 * Logicbroker
 *
 * @category    Community
 * @package     Logicbroker_Dropship360
 */
?>

<?php /* var $this Mage_Adminhtml_Block_System_Config_System_Storage_Media_Synchronize */ ?>
<div style="float:left"><?php echo $this->getSubmitButtonHtml() ?></div>
<script type="text/javascript">
//<![CDATA[
    Validation.addAllThese([
		['validate-url-logicbroker', 'Please enter a valid URL. Protocol is required (http://, https:// )', function (v) {
                v = (v || '').replace(/^\s+/, '').replace(/\s+$/, '');
                return Validation.get('IsEmpty').test(v) || /^(http|https):\/\/(([A-Z0-9]([A-Z0-9_-]*[A-Z0-9]|))(\.[A-Z0-9]([A-Z0-9_-]*[A-Z0-9]|))*)(:(\d+))?(\/[A-Z0-9~](([A-Z0-9_~-]|\.)*[A-Z0-9~]|))*\/?(.*)?$/i.test(v)
            }],
    ['validate-ftp-url-logicbroker', 'Please enter a valid URL. Protocol is required (ftp://, ftps:// )', function (v) {
                return Validation.get('IsEmpty').test(v) || /^(ftps|ftp):\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+.(com|org|net|dk|at|us|tv|info|uk|co.uk|biz|se)$)(:(\d+))?\/?/i.test(v) || /^(www)((\.[A-Z0-9][A-Z0-9_-]*)+.(com|org|net|dk|at|us|tv|info|uk|co.uk|biz|se)$)(:(\d+))?\/?/i.test(v)
            }]
    ]);
       
	var enableId = 'logicbroker_sourcing_cron_settings_upload_enabled'; 
	var buttonId = 'logicbroker_sourcing_cron_settings_upload_ftp_testconnection'; 
	var buttonObj = $('logicbroker_sourcing_cron_settings_upload_ftp_testconnection');
	 function checkButtonState(event) {
        var element = Event.element(event);

        if(element.value == '1'){
			enableSyncButton();
		}else
		{
			disableSyncButton();
		}

        
    }
  
	function enableSyncButton() {
        Form.Element.enable(buttonId);
		buttonObj.removeClassName('disabled');
    }

    function disableSyncButton() {
        Form.Element.disable(buttonId);
        buttonObj.addClassName('disabled');
    }

    Event.observe(window, 'load', function(){
        
        if($(enableId).value != '1'){
			disableSyncButton();
		}
        
    });
    $(enableId).observe('change', checkButtonState);	
    function synchronize(id) {
        
        if(!configForm.validate())
            {
                return ;
            }
            
        new Ajax.Request('<?php echo $this->getAjaxSyncUrl() ?>', {
            parameters:      $('config_edit_form').serialize(),
            method:     'post',
            onSuccess:  successFunc,
            onFailure:  failFunc
        });

         }
    
    function successFunc(response){
      var container = $('messages');
    var content = response.responseText.evalJSON();
	if(content.error)
        {
		$('messages').show();	
         container.update('<ul class="messages"><li class="error-msg"><ul><li><span>'+content.message+'</span></li></ul></li></ul>')
         container.scrollTo();
		buttonObj.innerHTML = '<span><spn>Unsuccessful Tested</span></span>'
         return;
        }else
		{
        buttonObj.innerHTML = '<span><spn>Successfully Tested</span></span>'
		 $('messages').hide();
        }
	
		}
	    
    function failFunc(){
        alert('Not able to connect to server please try again later');
    }
//]]>
</script>



