<?php 
/**
 * Logicbroker
 *
 * @category    Community
 * @package     Logicbroker_Dropship360
 */
?>
<?php 
$lbItemDescSort = $this->getHistory(); 
if(is_array($lbItemDescSort))
krsort($lbItemDescSort);
?>
<div class="entry-edit">
    <fieldset>
        <ul class="note-list">
		<?php if($this->getHistory()) : ?>
        <?php foreach ($lbItemDescSort as $item): ?>
            <li>
                <strong><?php echo Mage::helper('core')->formatDate($item['date'], 'medium', false);//echo $item['date']; ?></strong>
                <?php echo Mage::helper('core')->formatTime($item['date'], 'medium', false); ?><span class="separator">|</span>
                <strong><?php echo  $item['item_status']; ?></strong>
                <span class="separator">|</span>
                <small>
                    <strong class="subdue">
					<?php echo  Mage::getModel('sales/order_status')->load($item['order_status'], 'status')->getStoreLabel(); ?>
					  <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="" />
                    </strong>
                </small>
            </li>
        <?php endforeach; ?>
		<?php else : ?>
			<?php echo $this->__('No Records Found')?>
		<?php endif; ?>
        </ul>
    </fieldset>
</div>