<?php $dropshipVendorCollection = $this->getVendorCollection('yes'); ?>
<?php $nonDropshipVendorCollection = $this->getVendorCollection('no'); ?>
<style type="text/css">


</style>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<!-- <div id="warning-message"><ul class="messages"><li class="warning-msg"><ul><li><span>Cost Based sourcing rule is currently selected. Vendor ranking will only take effect when Rank Based sourcing rule is selected in the Sourcing Configuration page.</span></li></ul></li></ul></div>
<div id="notice-message"><ul class="messages"><li class="notice-msg"><ul><li><span>To remove a Drop Ship Vendor from dropship360 sourcing rule, drag it to the Non Drop Ship Vendors section on the right. To activate that vendor again, simply drag it back to the Drop Ship Vendors section.</span></li></ul></li></ul></div>
<div id="message"><ul class="messages"><li class="error-msg"><ul><li><span>You Have Unsubmitted Changes.</span></li></ul></li></ul></div> -->
